#! /usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup" if File.exist?(File.expand_path("Gemfile", __dir__))

require "detector"
require "detector/cli"
require "detector/identity"

Process.setproctitle Detector::Identity.version_label
Detector::CLI.start
