#! /usr/bin/env ruby
# frozen_string_literal: true

ENV["BUNDLE_GEMFILE"] ||= File.expand_path(File.join("..", "Gemfile"), __dir__)
require "bundler/setup" if File.exist?(ENV["BUNDLE_GEMFILE"])

require "detector"
require "detector/cli"
require "detector/identity"

Process.setproctitle Detector::Identity.version_label
Detector::CLI.start
